### ISSUE TITLE
Time formats

### ISSUE THREAD

**Issue by renenm** [restezconnectes/send-pdf-for-contact-form-7#34]
Hi @Florent73 ,

I have a problem with time formats.

I use <input> fields of type date and datetime in a form. In the mozilla docs (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) these fields always output the date in the format as the browser set here or in the format YYYY-MM-DD.

Without your plugin I would convert from the format YYYY-MM-DD to my format, whether in JavaScript or PHP. But since all inputs are transferred to your plugin, I can no longer format anything.

Example: In CF7 I have a date field, which is also displayed correctly in the frontend, as it needs: dd.mm.yyyy. In the PDF export it looks like this: YYYY-MM-DD.

Is there already an option to set that I overlooked or could you please add a function that you can format date and datetime afterwards?

Thank you very much!

**Comment by Florent73** [comment]
Hi!

I will trying this in local development.

Thanks

**Comment by Florent73** [comment]
Hi!

Use this tag for all date tag: [_format_your-date "D, d M y"], replace **your-date**..

Thanks

**Comment by whydontdoit** [comment]
in the last plugin version, this tag seems to works  no more on final PDF rendering

[_format_your-date "D, d M y"]

Any suggest?

Thanks

**Comment by Florent73** [comment]
Hi!

This tag [_format_your-date "D, d M y"] is just for email. See here : https://contactform7.com/date-field/

Thanks

**Comment by whydontdoit** [comment]
HI!

so what about your answer above

 https://github.com/Florent73/send-pdf-for-contact-form-7/issues/34#issuecomment-1370930486

in reply to example explained in https://github.com/Florent73/send-pdf-for-contact-form-7/issues/34#issue-1518841532 ?

I know that code
` [_format_your-date "D, d M y"] ` works in email

Question is : why in PDF body, made by plugin, date inputs are formatting only as YYYY-MM-DD, is there anyway to format in a different foramt? I’m not talking about date reference in general settings, but about date inputs passed from CF7 Form. I hope I was clear

![Screenshot 2023-11-17 alle 11 36 22](https://github.com/Florent73/send-pdf-for-contact-form-7/assets/91721029/b4623d3a-8d77-46ae-9192-3803a0b6e85c)

Thanks for your work!

**Comment by Florent73** [comment]
Hi!

For print date in PDF, I use date_i18n() function, with your setting in 'Select a date and time format'.

If you change this setting, what's appen? is this what you're trying to do?

Thanks

**Comment by Bqnaan** [comment]
Heya! Jumping in on this. Using the CF7 way (so like [_format_customdate "d-m-Y"]) is not working properly as seen here in the screenshot

![image](https://github.com/Florent73/send-pdf-for-contact-form-7/assets/52282663/554cba4e-d571-47c6-82d0-90e40bef746e)

It indeed works when i put this in the email that gets sent but if i were to put the tag in the PDF it does not work at all. I tried downgrading to version 1.0.0.1 and there it appears to work but then the plugin doesnt function as it should

**Comment by Florent73** [comment]
Hi!

You can testing now ! I adding _format_ tag.

See here :  : [ : https://demo.restezconnectes.fr/send-pdf-for-contact-form-7-debug-form/](https://demo.restezconnectes.fr/send-pdf-for-contact-form-7-debug-form/)

Thanks

**Comment by Bqnaan** [comment]
It works like a charm now, thanks a lot! Though I dont see the update on wordpress itself yet. I downloaded the code here from github and replaced the 1.0.1.4 source code by 1.0.1.5! But thanks a ton🙃

**Comment by whydontdoit** [comment]
> It works like a charm now, thanks a lot! Though I dont see the update on wordpress itself yet. I downloaded the code here from github and replaced the 1.0.1.4 source code by 1.0.1.5! But thanks a ton🙃

This resolves also issue I notified, thanks!
Hope to find new code made in next release 😄

**Comment by glidingjan** [comment]
Hey! I just updated on Version 1.0.1.6 and it seems to work. But i have two date-fields and just the first field gets into the PDF. The second one is ignored: 
![image](https://github.com/restezconnectes/send-pdf-for-contact-form-7/assets/152074885/c556edff-bc55-40b5-b65c-c95678cad7bd)

**Comment by whydontdoit** [comment]
Unfortunately I can confirm this behaviour...

   ---------- Messaggio originale ----------
   Da "glidingjan" ***@***.***
   A "restezconnectes/send-pdf-for-contact-form-7" ***@***.***
   Cc "whydontdoit" ***@***.***,"Comment" ***@***.***
   Data Sun, 26 Nov 2023 05:37:53 -0800
   Oggetto Re: [restezconnectes/send-pdf-for-contact-form-7] Time formats (Issue #34)

   Hey! I just updated on Version 1.0.1.6 and it seems to work. But i have two date-fields and just the first field gets into the PDF. The second one is ignored:
   image.png (view on web)

**Comment by whydontdoit** [comment]
Just a question for the developer...

   Is this wp.org's repo updated with last date features?
   https://it.wordpress.org/plugins/send-pdf-for-contact-form-7/#developers
   ---------- Messaggio originale ----------
   Da "glidingjan" ***@***.***
   A "restezconnectes/send-pdf-for-contact-form-7" ***@***.***
   Cc "whydontdoit" ***@***.***,"Comment" ***@***.***
   Data Sun, 26 Nov 2023 05:37:53 -0800
   Oggetto Re: [restezconnectes/send-pdf-for-contact-form-7] Time formats (Issue #34)

   Hey! I just updated on Version 1.0.1.6 and it seems to work. But i have two date-fields and just the first field gets into the PDF. The second one is ignored:
   image.png (view on web)

**Comment by whydontdoit** [comment]
Just a question for the developer...

   Is this wp.org's repo updated with last date features?
   https://it.wordpress.org/plugins/send-pdf-for-contact-form-7/#developers
![Screenshot 2023-11-27 alle 09 51 55](https://github.com/restezconnectes/send-pdf-for-contact-form-7/assets/91721029/847d571e-4602-4b5f-8be9-8012de56f7a2)

**Comment by restezconnectes** [comment]
Hi!

I solved the bug in GitHub version (always 1.0.1.6)

Thanks to test it!

**Comment by whydontdoit** [comment]
Sorry but, as I can see, in 1.0.1.6 version, bug is solved only for first date printed in pdf. From second date and following, format_{date_input} is not recognized, so shortocode is printed instead of the date 

see attachment
![Screenshot 2023-11-27 alle 14 44 18](https://github.com/restezconnectes/send-pdf-for-contact-form-7/assets/91721029/3dd0c36d-ed0f-460a-b5a2-dc2e5ee3d01a)

**Comment by restezconnectes** [comment]
Hi!

Can you testing with the 1.0.1.7 version?

Thanks

**Comment by whydontdoit** [comment]
Hi!

installed and tested 1.0.1.7 version.

I can confirm that date bug seems to be definitively solved. Good Job!

About testing other realease features:

= 1.0.1.7 =
1) Fix bug and defined constants WPCF7_ADMIN_READ_CAPABILITY / WPCF7_ADMIN_READ_WRITE_CAPABILITY
2) Fix bug redirection page after sending form
3) Fix bug "Desactivate line break auto" option reversed
4)Adding a option for desactivated line break for mail content


I find a bug which could be associated to point 2)
I mean: Page redirect now is correctly controlled by general preferences, but after this operation the generated pdf is automatically download (on new window redirect) even if this option is totally disabled on general options (see attachment)
![Screenshot 2023-11-29 alle 13 29 27](https://github.com/restezconnectes/send-pdf-for-contact-form-7/assets/91721029/46f75e7b-d5de-42a0-8e03-e75cbd44ac24)



Ps. Hoping to be usefull for project, I translate all strings reported here in ITALIAN
Translations: https://translate.wordpress.org/projects/wp-plugins/send-pdf-for-contact-form-7/


Thanks for your work!

**Comment by restezconnectes** [comment]
Hi!

Be carefull with a cache plugin. I've tested all of things and it's works.

Thanks

**Comment by whydontdoit** [comment]
Sorry... with cache free, I confirm issue

Strange thing is that 'download generated pdf' should not work with preferences I choose...

see attachment
![Screenshot 2023-11-29 alle 15 27 51](https://github.com/restezconnectes/send-pdf-for-contact-form-7/assets/91721029/a44d7ee6-9744-4f82-9232-9e4a1a277d3a)

**Comment by glidingjan** [comment]
Thank you for the fast solution of the date problem :)

**Comment by whydontdoit** [comment]
Thanks for solution too, but... when also an Italian translated version will be available for this beautiful plugin? ;-)

**Comment by restezconnectes** [comment]
Hi! 

You can complete your language here : [https://translate.wordpress.org/projects/wp-plugins/send-pdf-for-contact-form-7/](https://translate.wordpress.org/projects/wp-plugins/send-pdf-for-contact-form-7/)

Thanks

**Comment by whydontdoit** [comment]
done!

   now waiting for checking by someone...

   bye

   ---------- Messaggio originale ----------
   Da "Restez Connectés" ***@***.***
   A "restezconnectes/send-pdf-for-contact-form-7" ***@***.***
   Cc "whydontdoit" ***@***.***,"Comment" ***@***.***
   Data Tue, 19 Dec 2023 08:40:10 -0800
   Oggetto Re: [restezconnectes/send-pdf-for-contact-form-7] Time formats (Issue #34)

   Hi!

   You can complete your language here : https://translate.wordpress.org/projects/wp-plugins/send-pdf-for-contact-form-7/

   Thanks
