### ISSUE TITLE
Header settings get skipped when using automatic pagebreak

### ISSUE THREAD

**Issue by Nictrical** [restezconnectes/send-pdf-for-contact-form-7#55]
Hi,
I really like your plugin, but I found a little bug. When using the automatic pagebreak, the header and footer settings get skipped. When using [addpage] it all works fine. 

With my little knowledge of php I searched for the error in generate.php and found out, that the for-loop in line 201 is only active when [addpage] was used once. 

So to fix this, there should be a similar loop after line 231. I already tried fixing it, but like I already wrote, I don't have much knowledge in programming in php so sadly I didn't found a solution by myself. I really prefer to send you a solution already.

This should fix the following topics in the wordpress-support-forum: 

https://wordpress.org/support/topic/completely-different-pdf-is-sent-in-email-than-in-preview-pdf/
https://wordpress.org/support/topic/header-is-displayed-on-every-page/
https://wordpress.org/support/topic/pdf-name-not-applied-header-setting-not-working/

Keep up the great work!

**Comment by Florent73** [comment]
Hi!

I'm working on it!

Thanks

**Comment by Florent73** [comment]
Hi!

Can you testing with the last version 1.0.1.6?

Thanks

**Comment by Nictrical** [comment]
Hi, 

it's now working totally fine!

Thank you a lot!
