### ISSUE TITLE
Disable open PDF on submit form

### ISSUE THREAD

**Issue by btxtiger** [restezconnectes/send-pdf-for-contact-form-7#57]
Each time when I submit the form, a popup opens to show the PDF. I found no option to disable this behavior. The PDF is just for internal usage, not for the customer.

**Comment by restezconnectes** [comment]
Hi!

See this option: "Redirects directly to the PDF after sending the form?" and check "No"

Thanks

**Comment by btxtiger** [comment]
![image](https://github.com/restezconnectes/send-pdf-for-contact-form-7/assets/15804690/be4f2304-4f5f-4617-8cbd-07491ef2a50f)
maybe its missing a default in the code?

**Comment by restezconnectes** [comment]
Hi!

Have you a cache plugin? Can you delete cache?

Thanks

**Comment by btxtiger** [comment]
Deleting the cache did not help, its also not active while logged in.

I could fix it, by enable the option -> save -> disable the option -> save.

**Comment by restezconnectes** [comment]
Hi!

Ok. Because new checks have been implemented.

Sorry for that and this the good process for others.

Thanks

**Comment by benholtsclaw** [comment]
I still can't get this to work correctly. Nothing is grayed out. The correct options seem to be set.
![image](https://github.com/restezconnectes/send-pdf-for-contact-form-7/assets/723813/c20df876-8152-4600-981e-f473502345ae)
I'm still getting the PDF opening in a new window. The form redirects to itself with the CF7 message underneath and the pdf opens in a new window.
![image](https://github.com/restezconnectes/send-pdf-for-contact-form-7/assets/723813/4833f48d-b71f-474a-bc6f-35606fed9806)
I installed V.1.0.1.7 today.

**Comment by restezconnectes** [comment]
Hi!

I have updated send-pdf.php file.

I have sames [option in my form ](https://demo.restezconnectes.fr/send-pdf-for-contact-form-7-debug-form/)...

I'ts working. Can you replace send-pdf.php file?

Thanks
