### ISSUE TITLE
Footer only on every 2nd page

### ISSUE THREAD

**Issue by btxtiger** [restezconnectes/send-pdf-for-contact-form-7#58]
It seems the footer (for example page number) gets inserted only on every 2nd page (1, 3, 5, 7, 9). I tested it on multiple WP installations and could not find any other issue. 

I did **not** use the addpage code. 
I used very long text content (repeated `<p>HELLO</p>` 200 lines.

**Comment by restezconnectes** [comment]
Hi!

I'm working on it!

Thanks

**Comment by restezconnectes** [comment]
Hi!

Can you testing with the 1.0.1.9 version.

Thanks

**Comment by whydontdoit** [comment]
> Hi!
> 
> Can you testing with the 1.0.1.9 version.
> 
> Thanks

It seems to work for me

Thanks

**Comment by btxtiger** [comment]
@restezconnectes Where can I download the version? Thanks

**Comment by restezconnectes** [comment]
hi!

Here, GitHub version :)

**Comment by btxtiger** [comment]
Thank you, it works now 🚀
