### ISSUE TITLE
Date Field 

### ISSUE THREAD

**Issue by Ricco-S** [restezconnectes/send-pdf-for-contact-form-7#60]
Hello, 

i got some Error Message on submit Form from Mobile Devices from shortcode Tag in PDF Template: 
[Date]

Failed to parse time String DateTime
18. Januar 2024 could not be found in Database…

**Comment by restezconnectes** [comment]
Hi!

The good tag is [date] isn't it?

Thanks

**Comment by Ricco-S** [comment]
Yes we use [date] Field in the Textarea Field for Build the PDF from CF7 Data

**Comment by restezconnectes** [comment]
Hi!

The shortcode [date] is just a date displaying, it's no sending with your form and not a tag for database...

Thanks
