### ISSUE TITLE
Fixing the translations

### ISSUE THREAD

**Issue by btxtiger** [restezconnectes/send-pdf-for-contact-form-7#63]
Hi there,

I can speak English, German and French, and I find the English and German translations slightly inaccurate and partially very hard to understand. `

How can I contribute new translations to fix this?

**Comment by restezconnectes** [comment]
Hi!

You can here : [https://translate.wordpress.org/projects/wp-plugins/send-pdf-for-contact-form-7/](https://translate.wordpress.org/projects/wp-plugins/send-pdf-for-contact-form-7/)

Thanks

**Comment by btxtiger** [comment]
merci, je vais le regarder

**Comment by btxtiger** [comment]
L’allemand est complet. Je regarderai probablement l’anglais demain
