### ISSUE TITLE
General Settings: Same id for two switches, so one is not working

### ISSUE THREAD

**Issue by Vanois-be** [restezconnectes/send-pdf-for-contact-form-7#67]
Bonjour,

Send PDF for Contact Form 7 - Réglages V.1.0.2.8

Dans les Réglages Généraux, les deux paramètres suivant partage le même id "switch_insert_no"
- Conditional field for sending PDF file? (4eme option)
- Annuler l’envoi de données dans la base de données ?  (juste en dessous).

Si on switch "Annuler l'envoi dans la db" c'est "Conditional field..." qui switch.

See https://github.com/restezconnectes/send-pdf-for-contact-form-7/blob/master/views/send-pdf-admin.php
Line 424 and 461

Bien à toi,
François

**Comment by restezconnectes** [comment]
Bonjour,

Merci, je corrige cela rapidement et je mets à jour dans la foulée.

Cordialement

**Comment by restezconnectes** [comment]
Salut,

C'est maintenant réglé en téléchargeant à nouveau les fichiers de GitHub.

Cordialement
